// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njejkfeibjhzmwxqrvzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZWprZmVpYmpoem13eHFydnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzA1MTQsImV4cCI6MjA2NjEwNjUxNH0.QAqaBcQm3UqKBclfoeCwYGU7haJw6qyZ72GMda37CIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);